// Copyright 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
import styled from 'styled-components';
import { visuallyHidden } from '../../../utils/style';
export var HiddenCheckbox = styled.input(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  ", ";\n\n  &[aria-invalid='true'] + .ch-checkbox {\n    border: ", ";\n    box-shadow: ", ";\n  }\n"], ["\n  ", ";\n\n  &[aria-invalid='true'] + .ch-checkbox {\n    border: ", ";\n    box-shadow: ", ";\n  }\n"])), visuallyHidden, function (props) { return props.theme.inputs.error.border; }, function (props) { return props.theme.inputs.error.shadow; });
export var StyledCheckbox = styled.div(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n  background-color: ", ";\n  border: ", ";\n  border-radius: ", ";\n  box-shadow: ", ";\n  color: ", ";\n  display: inline-block;\n  height: 1rem;\n  position: relative;\n  width: 1rem;\n  transition: box-shadow 0.05s ease-in;\n\n  > svg {\n    left: -0.03125rem;\n    position: absolute;\n    transform: scale(1.5);\n  }\n\n  ", ":checked ~ & {\n    background-color: ", ";\n    border: ", ";\n    box-shadow: ", ";\n    color: ", ";\n  }\n\n  ", ":focus ~ & {\n    border: ", ";\n    box-shadow: ", ";\n  }\n"], ["\n  background-color: ", ";\n  border: ", ";\n  border-radius: ", ";\n  box-shadow: ", ";\n  color: ", ";\n  display: inline-block;\n  height: 1rem;\n  position: relative;\n  width: 1rem;\n  transition: box-shadow 0.05s ease-in;\n\n  > svg {\n    left: -0.03125rem;\n    position: absolute;\n    transform: scale(1.5);\n  }\n\n  ", ":checked ~ & {\n    background-color: ", ";\n    border: ", ";\n    box-shadow: ", ";\n    color: ", ";\n  }\n\n  ", ":focus ~ & {\n    border: ", ";\n    box-shadow: ", ";\n  }\n"])), function (props) { return props.theme.inputs.bgd; }, function (props) { return props.theme.inputs.border; }, function (props) { return props.theme.radii.default; }, function (props) { return props.theme.inputs.shadow; }, function (props) { return props.theme.inputs.fontColor; }, HiddenCheckbox, function (props) { return props.theme.inputs.checked.bgd; }, function (props) { return props.theme.inputs.checked.border; }, function (props) { return props.theme.inputs.checked.shadow; }, function (props) { return props.theme.inputs.checked.fontColor; }, HiddenCheckbox, function (props) { return props.theme.inputs.focus.border; }, function (props) { return props.theme.inputs.focus.shadow; });
var templateObject_1, templateObject_2;
//# sourceMappingURL=Styled.js.map