// Copyright 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
import { baseSpacing, baseStyles } from '../Base';
import styled, { css } from 'styled-components';
export var stack = css(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  &.ch-form-field-input,\n  &.ch-form-field-select,\n  &.ch-form-field-textarea {\n    display: flex;\n    flex-direction: column;\n\n    label {\n      display: block;\n      margin-bottom: 0.5rem;\n    }\n\n    input,\n    select {\n      width: 100%;\n    }\n  }\n\n  &.ch-form-field-checkbox {\n    display: grid;\n    grid-template-columns: 1.5rem 1fr;\n    grid-template-rows: auto;\n    gap: 0px 0.5rem;\n\n    .ch-checkbox {\n      grid-column: 1;\n      grid-row: 1;\n    }\n\n    .ch-checkbox-label {\n      line-height: 1.3;\n      grid-column: 2;\n    }\n\n    .ch-help-text {\n      grid-row: 2;\n      grid-column: 1/3;\n    }\n  }\n\n  &.ch-form-field-radiogroup {\n    flex-direction: column;\n\n    .ch-radio-wrapper {\n      display: block;\n      margin-bottom: 0.5rem;\n      padding-left: 0.125rem;\n      display: grid;\n      grid-template-columns: 1.5rem 1fr;\n      grid-template-rows: auto;\n\n      align-items: center;\n    }\n\n    .ch-radio-label {\n      margin-left: 1rem;\n      position: relative;\n      bottom: -0.5px;\n    }\n  }\n"], ["\n  &.ch-form-field-input,\n  &.ch-form-field-select,\n  &.ch-form-field-textarea {\n    display: flex;\n    flex-direction: column;\n\n    label {\n      display: block;\n      margin-bottom: 0.5rem;\n    }\n\n    input,\n    select {\n      width: 100%;\n    }\n  }\n\n  &.ch-form-field-checkbox {\n    display: grid;\n    grid-template-columns: 1.5rem 1fr;\n    grid-template-rows: auto;\n    gap: 0px 0.5rem;\n\n    .ch-checkbox {\n      grid-column: 1;\n      grid-row: 1;\n    }\n\n    .ch-checkbox-label {\n      line-height: 1.3;\n      grid-column: 2;\n    }\n\n    .ch-help-text {\n      grid-row: 2;\n      grid-column: 1/3;\n    }\n  }\n\n  &.ch-form-field-radiogroup {\n    flex-direction: column;\n\n    .ch-radio-wrapper {\n      display: block;\n      margin-bottom: 0.5rem;\n      padding-left: 0.125rem;\n      display: grid;\n      grid-template-columns: 1.5rem 1fr;\n      grid-template-rows: auto;\n\n      align-items: center;\n    }\n\n    .ch-radio-label {\n      margin-left: 1rem;\n      position: relative;\n      bottom: -0.5px;\n    }\n  }\n"])));
export var horizontal = css(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n  @media (max-width: 599px) {\n    ", ";\n  }\n\n  @media (min-width: 600px) {\n    &.ch-form-field-input,\n    &.ch-form-field-select,\n    &.ch-form-field-textarea,\n    &.ch-form-field-checkbox {\n      display: grid;\n      grid-template-columns: 30% 1fr;\n      grid-template-rows: auto;\n      gap: 0px 0.5rem;\n      align-items: center;\n\n      input {\n        width: 100%;\n      }\n\n      .ch-help-text {\n        grid-column: 2;\n      }\n    }\n\n    &.ch-form-field-radiogroup {\n      flex-wrap: wrap;\n\n      fieldset {\n        width: 100%;\n      }\n\n      .ch-radio-wrapper {\n        display: grid;\n        grid-template-columns: 30% 1fr;\n        grid-template-rows: auto;\n        gap: 0px 0.5rem;\n        align-items: center;\n        margin-bottom: 0.5rem;\n      }\n\n      .ch-radio {\n        grid-column: 2;\n        grid-row: 1;\n        margin-top: -4px;\n      }\n\n      .ch-radio-label {\n        grid-column: 1;\n        padding-right: 1rem;\n        margin-left: 0;\n      }\n\n      .ch-help-text {\n        width: 100%;\n      }\n    }\n  }\n"], ["\n  @media (max-width: 599px) {\n    ", ";\n  }\n\n  @media (min-width: 600px) {\n    &.ch-form-field-input,\n    &.ch-form-field-select,\n    &.ch-form-field-textarea,\n    &.ch-form-field-checkbox {\n      display: grid;\n      grid-template-columns: 30% 1fr;\n      grid-template-rows: auto;\n      gap: 0px 0.5rem;\n      align-items: center;\n\n      input {\n        width: 100%;\n      }\n\n      .ch-help-text {\n        grid-column: 2;\n      }\n    }\n\n    &.ch-form-field-radiogroup {\n      flex-wrap: wrap;\n\n      fieldset {\n        width: 100%;\n      }\n\n      .ch-radio-wrapper {\n        display: grid;\n        grid-template-columns: 30% 1fr;\n        grid-template-rows: auto;\n        gap: 0px 0.5rem;\n        align-items: center;\n        margin-bottom: 0.5rem;\n      }\n\n      .ch-radio {\n        grid-column: 2;\n        grid-row: 1;\n        margin-top: -4px;\n      }\n\n      .ch-radio-label {\n        grid-column: 1;\n        padding-right: 1rem;\n        margin-left: 0;\n      }\n\n      .ch-help-text {\n        width: 100%;\n      }\n    }\n  }\n"])), stack);
export var inputOnly = css(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n  &.ch-form-field-input,\n  &.ch-form-field-select,\n  &.ch-form-field-textarea {\n    display: flex;\n    flex-direction: column;\n\n    input {\n      width: 100%;\n    }\n  }\n\n  &.ch-form-field-checkbox {\n    display: flex;\n    flex-wrap: wrap;\n    align-items: center;\n\n    .ch-checkbox {\n      order: 1;\n    }\n\n    .ch-checkbox-label {\n      order: 2;\n      padding-left: 1rem;\n    }\n\n    .ch-help-text {\n      width: 100%;\n      order: 3;\n    }\n  }\n\n  &.ch-form-field-radiogroup {\n    flex-direction: column;\n\n    .ch-radio-wrapper {\n      display: block;\n      margin-bottom: 0.5rem;\n    }\n\n    .ch-radio-label {\n      margin-left: 1rem;\n    }\n  }\n"], ["\n  &.ch-form-field-input,\n  &.ch-form-field-select,\n  &.ch-form-field-textarea {\n    display: flex;\n    flex-direction: column;\n\n    input {\n      width: 100%;\n    }\n  }\n\n  &.ch-form-field-checkbox {\n    display: flex;\n    flex-wrap: wrap;\n    align-items: center;\n\n    .ch-checkbox {\n      order: 1;\n    }\n\n    .ch-checkbox-label {\n      order: 2;\n      padding-left: 1rem;\n    }\n\n    .ch-help-text {\n      width: 100%;\n      order: 3;\n    }\n  }\n\n  &.ch-form-field-radiogroup {\n    flex-direction: column;\n\n    .ch-radio-wrapper {\n      display: block;\n      margin-bottom: 0.5rem;\n    }\n\n    .ch-radio-label {\n      margin-left: 1rem;\n    }\n  }\n"])));
var layoutMap = {
    stack: stack,
    horizontal: horizontal,
    'input-only': inputOnly
};
export var StyledFormField = styled.div(templateObject_4 || (templateObject_4 = __makeTemplateObject(["\n  display: flex;\n  margin-bottom: 1rem;\n  position: relative;\n\n  fieldset {\n    margin: 0;\n    border: none;\n    padding: 0;\n  }\n\n  .ch-help-text {\n    font-size: ", ";\n    margin-top: 0.5rem;\n    color: ", ";\n  }\n\n  legend {\n    font-size: ", ";\n    color: ", ";\n    margin-bottom: 0.5rem;\n  }\n\n  ", "\n\n  ", "\n  ", "\n"], ["\n  display: flex;\n  margin-bottom: 1rem;\n  position: relative;\n\n  fieldset {\n    margin: 0;\n    border: none;\n    padding: 0;\n  }\n\n  .ch-help-text {\n    font-size: ", ";\n    margin-top: 0.5rem;\n    color: ",
    ";\n  }\n\n  legend {\n    font-size: ", ";\n    color: ", ";\n    margin-bottom: 0.5rem;\n  }\n\n  ", "\n\n  ", "\n  ", "\n"])), function (props) { return props.theme.fontSizes.small.fontSize; }, function (props) {
    return !!props.error
        ? props.theme.inputs.error.fontColor
        : props.theme.inputs.fontColor;
}, function (props) { return props.theme.fontSizes.text.fontSize; }, function (props) { return props.theme.inputs.fontColor; }, function (props) { return !!props.layout && layoutMap[props.layout]; }, baseSpacing, baseStyles);
var templateObject_1, templateObject_2, templateObject_3, templateObject_4;
//# sourceMappingURL=Styled.js.map