// Copyright 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
import { fadeAnimation, slideDownAndScaleUp } from '../../../utils/animations';
import styled from 'styled-components';
export var StyledModal = styled.div(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  position: fixed;\n  top: 0;\n  left: 0;\n  width: 100%;\n  height: 100%;\n  background-color: ", ";\n  display: flex;\n  align-items: center;\n  justify-content: center;\n  z-index: ", ";\n  overflow-x: hidden;\n  animation: ", " 0.25s ease 0s forwards;\n  will-change: opacity;\n\n  > section {\n    position: relative;\n    display: flex;\n    flex-direction: column;\n    justify-content: center;\n    border-radius: ", ";\n    color: ", ";\n    background-color: ", ";\n    width: ", ";\n    box-shadow: ", ";\n    max-width: ", ";\n    height: ", ";\n    max-height: ", ";\n    will-change: transform, opacity;\n    animation: ", " 0.15s ease 0s forwards;\n\n    @media only screen and (max-height: 25rem) {\n      position: absolute;\n      top: 2rem;\n      height: auto;\n      max-height: none;\n    }\n  }\n"], ["\n  position: fixed;\n  top: 0;\n  left: 0;\n  width: 100%;\n  height: 100%;\n  background-color: ", ";\n  display: flex;\n  align-items: center;\n  justify-content: center;\n  z-index: ", ";\n  overflow-x: hidden;\n  animation: ", " 0.25s ease 0s forwards;\n  will-change: opacity;\n\n  > section {\n    position: relative;\n    display: flex;\n    flex-direction: column;\n    justify-content: center;\n    border-radius: ", ";\n    color: ", ";\n    background-color: ", ";\n    width: ", ";\n    box-shadow: ", ";\n    max-width: ",
    ";\n    height: ",
    ";\n    max-height: ", ";\n    will-change: transform, opacity;\n    animation: ", " 0.15s ease 0s forwards;\n\n    @media only screen and (max-height: 25rem) {\n      position: absolute;\n      top: 2rem;\n      height: auto;\n      max-height: none;\n    }\n  }\n"])), function (props) { return props.theme.modal.wrapperBgd; }, function (props) { return props.theme.zIndex.modal; }, fadeAnimation, function (props) { return props.theme.radii.default; }, function (props) { return props.theme.modal.text; }, function (props) { return props.theme.modal.bgd; }, function (props) { return props.theme.modalSizes[props.size || 'md'].width; }, function (props) { return props.theme.modal.shadow; }, function (props) {
    return props.size === 'fullscreen'
        ? props.theme.modalSizes[props.size].width
        : '90vw';
}, function (props) {
    return props.size === 'fullscreen'
        ? props.theme.modalSizes[props.size].height
        : 'auto';
}, function (props) { return props.theme.modalSizes[props.size || 'md'].height; }, slideDownAndScaleUp);
export var StyledModalHeader = styled.header(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n  padding: 1rem 1.5rem;\n\n  .ch-close-button {\n    position: absolute;\n    right: 1.55rem;\n    top: 1rem;\n  }\n\n  .ch-title {\n    padding-right: 2rem;\n    margin: 0;\n    font-size: ", ";\n    font-weight: ", ";\n  }\n"], ["\n  padding: 1rem 1.5rem;\n\n  .ch-close-button {\n    position: absolute;\n    right: 1.55rem;\n    top: 1rem;\n  }\n\n  .ch-title {\n    padding-right: 2rem;\n    margin: 0;\n    font-size: ", ";\n    font-weight: ", ";\n  }\n"])), function (props) { return props.theme.modal.titleSize; }, function (props) { return props.theme.modal.titleWeight; });
export var StyledModalBody = styled.div(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n  font-size: ", ";\n  line-height: ", ";\n  padding: 0 1.5rem;\n  flex-grow: 1;\n  overflow-y: auto;\n"], ["\n  font-size: ", ";\n  line-height: ", ";\n  padding: 0 1.5rem;\n  flex-grow: 1;\n  overflow-y: auto;\n"])), function (props) { return props.theme.fontSizes.text.fontSize; }, function (props) { return props.theme.fontSizes.text.lineHeight; });
export var StyledModalButtonGroup = styled.footer(templateObject_4 || (templateObject_4 = __makeTemplateObject(["\n  padding: 1.5rem;\n  border-top: 1px solid ", ";\n  display: flex;\n  flex-direction: row-reverse;\n  justify-content: space-between;\n\n  div:first-child {\n    display: flex;\n    flex-direction: row-reverse;\n  }\n\n  button + button {\n    margin: 0 0.5rem 0 0.5rem;\n  }\n\n  @media (max-width: 35rem) {\n    flex-direction: column;\n\n    button {\n      width: 100%;\n    }\n\n    div:first-child {\n      display: flex;\n      flex-direction: column;\n    }\n\n    button + button,\n    div + div {\n      margin: 0.5rem 0 0;\n    }\n  }\n"], ["\n  padding: 1.5rem;\n  border-top: 1px solid ", ";\n  display: flex;\n  flex-direction: row-reverse;\n  justify-content: space-between;\n\n  div:first-child {\n    display: flex;\n    flex-direction: row-reverse;\n  }\n\n  button + button {\n    margin: 0 0.5rem 0 0.5rem;\n  }\n\n  @media (max-width: 35rem) {\n    flex-direction: column;\n\n    button {\n      width: 100%;\n    }\n\n    div:first-child {\n      display: flex;\n      flex-direction: column;\n    }\n\n    button + button,\n    div + div {\n      margin: 0.5rem 0 0;\n    }\n  }\n"])), function (props) { return props.theme.modal.border; });
var templateObject_1, templateObject_2, templateObject_3, templateObject_4;
//# sourceMappingURL=Styled.js.map