// Copyright 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
import { ellipsis } from '../../../utils/style';
import styled from 'styled-components';
export var StyledPopOverMenu = styled.ul(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  width: fit-content;\n  max-width: 22rem;\n  background-color: ", ";\n  border: ", ";\n  margin: 0;\n  border-radius: 0.25rem;\n  backdrop-filter: blur(1rem);\n  list-style: none;\n  padding: 0.5rem 0;\n  box-shadow: ", ";\n  z-index: ", ";\n  display: table;\n  overflow: inherit;\n"], ["\n  width: fit-content;\n  max-width: 22rem;\n  background-color: ", ";\n  border: ", ";\n  margin: 0;\n  border-radius: 0.25rem;\n  backdrop-filter: blur(1rem);\n  list-style: none;\n  padding: 0.5rem 0;\n  box-shadow: ", ";\n  z-index: ", ";\n  display: table;\n  overflow: inherit;\n"])), function (props) { return props.theme.popOver.menuBgd; }, function (props) { return props.theme.popOver.menuBorder; }, function (props) { return props.theme.popOver.shadow; }, function (props) { return props.theme.zIndex.popOver; });
export var StyledPopOverToggle = styled.button(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n  background-color: transparent;\n  padding: 0;\n  border: none;\n  cursor: pointer;\n  &:focus {\n    outline: 0;\n  }\n"], ["\n  background-color: transparent;\n  padding: 0;\n  border: none;\n  cursor: pointer;\n  &:focus {\n    outline: 0;\n  }\n"])));
export var StyledPopOverItem = styled.li(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n  height: 2rem;\n  position: relative;\n\n  button,\n  a {\n    width: 100%;\n    height: 100%;\n    display: flex;\n    align-items: center;\n    border: none;\n    cursor: pointer;\n    background-color: ", ";\n    color: ", ";\n    line-height: ", ";\n    font-size: ", ";\n    padding: 0 2.5rem;\n    text-decoration: none;\n    outline: 0;\n\n    &:hover,\n    &:focus {\n      background-color: ", ";\n      color: ", ";\n      outline: 0;\n    }\n  }\n\n  a {\n    width: unset;\n  }\n\n  .ch-content > * {\n    ", ";\n  }\n\n  .ch-check {\n    position: absolute;\n    left: 0.5rem;\n    width: 1.5rem;\n    height: 1.5rem;\n    top: 0.33rem;\n  }\n\n  &:hover .ch-check g,\n  &:focus .ch-check g {\n    fill: ", ";\n  }\n"], ["\n  height: 2rem;\n  position: relative;\n\n  button,\n  a {\n    width: 100%;\n    height: 100%;\n    display: flex;\n    align-items: center;\n    border: none;\n    cursor: pointer;\n    background-color: ", ";\n    color: ", ";\n    line-height: ", ";\n    font-size: ", ";\n    padding: 0 2.5rem;\n    text-decoration: none;\n    outline: 0;\n\n    &:hover,\n    &:focus {\n      background-color: ", ";\n      color: ", ";\n      outline: 0;\n    }\n  }\n\n  a {\n    width: unset;\n  }\n\n  .ch-content > * {\n    ", ";\n  }\n\n  .ch-check {\n    position: absolute;\n    left: 0.5rem;\n    width: 1.5rem;\n    height: 1.5rem;\n    top: 0.33rem;\n  }\n\n  &:hover .ch-check g,\n  &:focus .ch-check g {\n    fill: ", ";\n  }\n"])), function (props) { return props.theme.popOver.itemBgd; }, function (props) { return props.theme.popOver.itemText; }, function (props) { return props.theme.fontSizes.text.lineHeight; }, function (props) { return props.theme.fontSizes.text.fontSize; }, function (props) { return props.theme.popOver.active.itemBgd; }, function (props) { return props.theme.popOver.active.itemText; }, ellipsis, function (props) { return props.theme.popOver.active.itemText; });
export var StyledSubMenu = styled(StyledPopOverItem)(templateObject_4 || (templateObject_4 = __makeTemplateObject(["\n  > span {\n    width: 100%;\n    height: 100%;\n    display: block;\n    height: 2rem;\n  }\n\n  > button {\n    position: relative;\n  }\n\n  .ch-caret {\n    position: absolute;\n    width: 1.5rem;\n    height: 1.5rem;\n    right: 0;\n    color: inherit;\n    fill: inherit;\n  }\n"], ["\n  > span {\n    width: 100%;\n    height: 100%;\n    display: block;\n    height: 2rem;\n  }\n\n  > button {\n    position: relative;\n  }\n\n  .ch-caret {\n    position: absolute;\n    width: 1.5rem;\n    height: 1.5rem;\n    right: 0;\n    color: inherit;\n    fill: inherit;\n  }\n"])));
export var StyledPopOverHeader = styled.header(templateObject_5 || (templateObject_5 = __makeTemplateObject(["\n  border-bottom: 0.0625rem solid ", ";\n  margin-bottom: 0.75rem;\n\n  img {\n    width: 100%;\n    display: inline-block;\n    margin-top: -0.5rem;\n    border-radius: 0.25rem 0.25rem 0 0;\n  }\n\n  img + .ch-title {\n    margin-top: 0.75rem;\n  }\n\n  .ch-title {\n    ", ";\n    padding: 0 2.5rem;\n    margin-top: 0.5rem;\n    margin-bottom: 0;\n    color: ", ";\n    font-size: 1.18125rem;\n    line-height: ", ";\n  }\n\n  .ch-subtitle {\n    ", ";\n    padding: 0 2.5rem;\n    color: #616672;\n    font-size: ", ";\n    line-height: ", ";\n    line-height: 1.43;\n    margin: 0 0 1rem;\n  }\n"], ["\n  border-bottom: 0.0625rem solid ", ";\n  margin-bottom: 0.75rem;\n\n  img {\n    width: 100%;\n    display: inline-block;\n    margin-top: -0.5rem;\n    border-radius: 0.25rem 0.25rem 0 0;\n  }\n\n  img + .ch-title {\n    margin-top: 0.75rem;\n  }\n\n  .ch-title {\n    ", ";\n    padding: 0 2.5rem;\n    margin-top: 0.5rem;\n    margin-bottom: 0;\n    color: ", ";\n    font-size: 1.18125rem;\n    line-height: ", ";\n  }\n\n  .ch-subtitle {\n    ", ";\n    padding: 0 2.5rem;\n    color: #616672;\n    font-size: ", ";\n    line-height: ", ";\n    line-height: 1.43;\n    margin: 0 0 1rem;\n  }\n"])), function (props) { return props.theme.popOver.separator; }, ellipsis, function (props) { return props.theme.popOver.titleText; }, function (props) { return props.theme.fontSizes.text.lineHeight; }, ellipsis, function (props) { return props.theme.fontSizes.text.fontSize; }, function (props) { return props.theme.fontSizes.text.lineHeight; });
export var StyledPopOverSeparator = styled.li(templateObject_6 || (templateObject_6 = __makeTemplateObject(["\n  margin: 0;\n  border-width: 0.0625rem 0 0 0;\n  border-style: solid;\n  border-color: ", ";\n  margin-bottom: 0.75rem;\n  opacity: 0.8;\n"], ["\n  margin: 0;\n  border-width: 0.0625rem 0 0 0;\n  border-style: solid;\n  border-color: ", ";\n  margin-bottom: 0.75rem;\n  opacity: 0.8;\n"])), function (props) { return props.theme.popOver.separator; });
var templateObject_1, templateObject_2, templateObject_3, templateObject_4, templateObject_5, templateObject_6;
//# sourceMappingURL=Styled.js.map