// Copyright 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
import { baseSpacing, baseStyles } from '../Base';
import { ellipsis } from '../../../utils/style';
import styled from 'styled-components';
export var StyledVideoTile = styled.div(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  height: 100%;\n  width: 100%;\n  position: relative;\n  background: ", ";\n\n  video {\n    position: absolute;\n    top: 0;\n    left: 0;\n    right: 0;\n    bottom: 0;\n    width: 100%;\n    height: 100%;\n    object-fit: ", "};\n  }\n\n  .ch-icon {\n    width: 1.5rem;\n    height: 1.5rem;\n    display: inline-block;\n    background-color: papayawhip; /* TODO: figure out what this is supposed to be */\n    margin-right: 0.5rem;\n    flex: 0 0 1.5rem;\n  }\n\n  .ch-nameplate {\n    backdrop-filter: blur(20px);\n    background-color: rgba(46, 47, 52, 0.85);\n    border-radius: 0.25rem;\n    bottom: 0.5rem;\n    color: ", ";\n    left: 0.5rem;\n    max-width: calc(100% - 2rem);\n    padding: 0.5rem;\n    position: absolute;\n\n    div {\n      ", ";\n      display: flex;\n      align-items: center;\n    }\n\n    .ch-text {\n      font-size: ", ";\n      ", ";\n      margin: 0;\n    }\n  }\n\n  ", "\n  ", "\n"], ["\n  height: 100%;\n  width: 100%;\n  position: relative;\n  background: ", ";\n\n  video {\n    position: absolute;\n    top: 0;\n    left: 0;\n    right: 0;\n    bottom: 0;\n    width: 100%;\n    height: 100%;\n    object-fit: ", "};\n  }\n\n  .ch-icon {\n    width: 1.5rem;\n    height: 1.5rem;\n    display: inline-block;\n    background-color: papayawhip; /* TODO: figure out what this is supposed to be */\n    margin-right: 0.5rem;\n    flex: 0 0 1.5rem;\n  }\n\n  .ch-nameplate {\n    backdrop-filter: blur(20px);\n    background-color: rgba(46, 47, 52, 0.85);\n    border-radius: 0.25rem;\n    bottom: 0.5rem;\n    color: ", ";\n    left: 0.5rem;\n    max-width: calc(100% - 2rem);\n    padding: 0.5rem;\n    position: absolute;\n\n    div {\n      ", ";\n      display: flex;\n      align-items: center;\n    }\n\n    .ch-text {\n      font-size: ", ";\n      ", ";\n      margin: 0;\n    }\n  }\n\n  ", "\n  ", "\n"])), function (props) { return props.theme.colors.greys.grey100; }, function (props) { return props.objectFit || 'cover'; }, function (props) { return props.theme.colors.greys.white; }, ellipsis, function (props) { return props.theme.fontSizes.text.fontSize; }, ellipsis, baseSpacing, baseStyles);
var templateObject_1;
//# sourceMappingURL=Styled.js.map