// Copyright 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
import { baseSpacing, baseStyles } from '../../Base';
import styled from 'styled-components';
export var StyledChatBubbleContainer = styled.div(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  display: flex;\n  flex-direction: row;\n  font-size: 0.65rem;\n  margin-left: 1rem;\n  align-items: center;\n  background-color: ", ";\n  width: 100%;\n\n  .ch-timestamp {\n    padding-right: ", ";\n  }\n\n  .ch-popover-toggle {\n    height: 1.5rem;\n  }\n\n  ", "\n  ", "\n"], ["\n  display: flex;\n  flex-direction: row;\n  font-size: 0.65rem;\n  margin-left: 1rem;\n  align-items: center;\n  background-color: ", ";\n  width: 100%;\n\n  .ch-timestamp {\n    padding-right: ", ";\n  }\n\n  .ch-popover-toggle {\n    height: 1.5rem;\n  }\n\n  ", "\n  ", "\n"])), function (props) { return props.theme.chatBubble.container.bgd; }, function (props) { return (props.actions ? '1rem' : '2.5rem'); }, baseSpacing, baseStyles);
export var StyledChatBubble = styled.div(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n  background-color: ", ";\n  padding: 0.625rem 1rem;\n  border-radius: 4px;\n  width: fit-content;\n  color: ", ";\n  box-shadow: 0 1px 4px 0 rgba(0, 0, 0, 0.1);\n  line-height: 20px;\n  width: ", ";\n  max-width: 70.6%;\n  font-size: 0.875rem;\n  position: relative;\n  margin-bottom: ", ";\n  overflow-wrap: break-word;\n  word-break: break-word;\n  hyphens: auto;\n\n  & .ch-sender-name {\n    font-weight: bold;\n    margin-bottom: 0.5rem;\n  }\n\n  & svg {\n    position: absolute;\n    height: 19px;\n    width: 11px;\n    margin-top: -14px;\n    margin-left: -25px;\n\n    & .ch-chat-bubble-tail {\n      fill: ", ";\n    }\n  }\n\n  .ch-input {\n    width: 100%;\n  }\n\n  .ch-edit-buttons {\n    position: absolute;\n    margin-top: 1rem;\n    display: flex;\n    flex-direction: row-reverse;\n    width: 10rem;\n    justify-content: space-between;\n  }\n\n  ", ";\n  ", ";\n"], ["\n  background-color: ", ";\n  padding: 0.625rem 1rem;\n  border-radius: 4px;\n  width: fit-content;\n  color: ", ";\n  box-shadow: 0 1px 4px 0 rgba(0, 0, 0, 0.1);\n  line-height: 20px;\n  width: ", ";\n  max-width: 70.6%;\n  font-size: 0.875rem;\n  position: relative;\n  margin-bottom: ", ";\n  overflow-wrap: break-word;\n  word-break: break-word;\n  hyphens: auto;\n\n  & .ch-sender-name {\n    font-weight: bold;\n    margin-bottom: 0.5rem;\n  }\n\n  & svg {\n    position: absolute;\n    height: 19px;\n    width: 11px;\n    margin-top: -14px;\n    margin-left: -25px;\n\n    & .ch-chat-bubble-tail {\n      fill: ", ";\n    }\n  }\n\n  .ch-input {\n    width: 100%;\n  }\n\n  .ch-edit-buttons {\n    position: absolute;\n    margin-top: 1rem;\n    display: flex;\n    flex-direction: row-reverse;\n    width: 10rem;\n    justify-content: space-between;\n  }\n\n  ", ";\n  ", ";\n"])), function (props) { return props.theme.chatBubble[props.variant].bgd; }, function (props) { return props.theme.chatBubble[props.variant].fontColor; }, function (props) { return (props.editable ? '100%' : 'fit-content'); }, function (props) { return (props.editable ? '4rem' : 'unset'); }, function (props) { return props.theme.chatBubble[props.variant].bgd; }, baseSpacing, baseStyles);
export var StyledChatBubbleInfo = styled.div(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n  display: flex;\n  margin-right: 0.5rem;\n  margin-left: auto;\n  color: ", ";\n  align-items: center;\n\n  & .ch-message-actions {\n    border: 1px solid transparent;\n    border-radius: 50%;\n  }\n\n  & button:hover .ch-message-actions {\n    background-color: ", ";\n\n    & g {\n      fill: ", ";\n    }\n  }\n\n  & button:focus .ch-message-actions {\n    border: 1px solid ", ";\n    border-radius: 50%;\n  }\n\n  & .ch-message-actions g {\n    fill: ", ";\n  }\n\n  & .ch-message-actions.isOpen {\n    background-color: ", ";\n    border-radius: 50%;\n\n    & g {\n      fill: ", ";\n    }\n  }\n"], ["\n  display: flex;\n  margin-right: 0.5rem;\n  margin-left: auto;\n  color: ", ";\n  align-items: center;\n\n  & .ch-message-actions {\n    border: 1px solid transparent;\n    border-radius: 50%;\n  }\n\n  & button:hover .ch-message-actions {\n    background-color: ", ";\n\n    & g {\n      fill: ", ";\n    }\n  }\n\n  & button:focus .ch-message-actions {\n    border: 1px solid ", ";\n    border-radius: 50%;\n  }\n\n  & .ch-message-actions g {\n    fill: ", ";\n  }\n\n  & .ch-message-actions.isOpen {\n    background-color: ", ";\n    border-radius: 50%;\n\n    & g {\n      fill: ", ";\n    }\n  }\n"])), function (props) { return props.theme.chatBubble.container.fontColor; }, function (props) { return props.theme.buttons.icon.hover.bgd; }, function (props) { return props.theme.buttons.icon.hover.text; }, function (props) { return props.theme.colors.primary.dark; }, function (props) { return props.theme.chatBubble.container.fontColor; }, function (props) { return props.theme.buttons.icon.active.bgd; }, function (props) { return props.theme.buttons.icon.active.text; });
var templateObject_1, templateObject_2, templateObject_3;
//# sourceMappingURL=Styled.js.map