// Copyright 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
import { baseSpacing, baseStyles } from '../Base';
import { ellipsis } from '../../../utils/style';
import styled from 'styled-components';
export var StyledRoster = styled.div(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  width: 100%;\n  height: 100%;\n  padding-bottom: 1rem;\n  overflow-y: auto;\n  background-color: ", ";\n  box-shadow: 1rem 1rem 3.75rem 0 rgba(0, 0, 0, 0.1);\n  border-left: 0.0625rem solid ", ";\n  border-right: 0.0625rem solid ", ";\n\n  ", " {\n    width: ", ";\n  }\n\n  ", "\n  ", "\n"], ["\n  width: 100%;\n  height: 100%;\n  padding-bottom: 1rem;\n  overflow-y: auto;\n  background-color: ", ";\n  box-shadow: 1rem 1rem 3.75rem 0 rgba(0, 0, 0, 0.1);\n  border-left: 0.0625rem solid ", ";\n  border-right: 0.0625rem solid ", ";\n\n  ", " {\n    width: ", ";\n  }\n\n  ", "\n  ", "\n"])), function (props) { return props.theme.roster.bgd; }, function (props) { return props.theme.roster.containerBorder; }, function (props) { return props.theme.roster.containerBorder; }, function (_a) {
    var theme = _a.theme;
    return theme.mediaQueries.min.md;
}, function (props) { return props.theme.roster.maxWidth; }, baseSpacing, baseStyles);
export var StyledTitle = styled.span(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n  display: inline-block;\n  margin: 0 0.625rem 0 0;\n  font-weight: 600;\n  font-size: 0.675rem;\n  color: ", ";\n"], ["\n  display: inline-block;\n  margin: 0 0.625rem 0 0;\n  font-weight: 600;\n  font-size: 0.675rem;\n  color: ", ";\n"])), function (props) { return props.theme.roster.secondaryText; });
export var StyledGroupWrapper = styled.div(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n  margin: 0 0.5rem;\n\n  & + & {\n    margin-top: 1rem;\n  }\n\n  ", "\n  ", "\n"], ["\n  margin: 0 0.5rem;\n\n  & + & {\n    margin-top: 1rem;\n  }\n\n  ", "\n  ", "\n"])), baseSpacing, baseStyles);
export var StyledGroup = styled.div(templateObject_4 || (templateObject_4 = __makeTemplateObject(["\n  background-color: ", ";\n  border-radius: ", ";\n\n  ", "\n  ", "\n"], ["\n  background-color: ", ";\n  border-radius: ", ";\n\n  ", "\n  ", "\n"])), function (props) { return props.theme.roster.fgd; }, function (props) { return props.theme.radii.default; }, baseSpacing, baseStyles);
export var StyledHeader = styled.div(templateObject_5 || (templateObject_5 = __makeTemplateObject(["\n  position: relative;\n  display: flex;\n  align-items: center;\n  padding: 0.75rem 1rem;\n  margin-bottom: 0.5rem;\n  border-bottom: 0.0625rem solid ", ";\n\n  .ch-title {\n    font-size: 0.875rem;\n    color: ", ";\n    ", "\n    ", ";\n  }\n\n  .ch-badge {\n    margin-left: 0.5rem;\n    ", "\n  }\n\n  .ch-buttons {\n    margin-left: auto;\n    display: flex;\n\n    > * {\n      margin-left: 0.5rem;\n    }\n\n    ", "\n  }\n\n  .ch-search-wrapper {\n    position: absolute !important;\n    bottom: 0.75rem;\n    left: 0.5rem;\n    right: 0.5rem;\n\n    .ch-search-input {\n      flex: 1;\n\n      input {\n        width: 100%;\n      }\n    }\n\n    .ch-search-close {\n      margin-left: 0.5rem;\n    }\n  }\n\n  .ch-navigation-icon {\n    margin-right: 0.5rem;\n    margin-left: -0.5rem;\n\n    ", " {\n      display: none;\n    }\n  }\n\n  ", "\n  ", "\n"], ["\n  position: relative;\n  display: flex;\n  align-items: center;\n  padding: 0.75rem 1rem;\n  margin-bottom: 0.5rem;\n  border-bottom: 0.0625rem solid ", ";\n\n  .ch-title {\n    font-size: 0.875rem;\n    color: ", ";\n    ", "\n    ", ";\n  }\n\n  .ch-badge {\n    margin-left: 0.5rem;\n    ", "\n  }\n\n  .ch-buttons {\n    margin-left: auto;\n    display: flex;\n\n    > * {\n      margin-left: 0.5rem;\n    }\n\n    ", "\n  }\n\n  .ch-search-wrapper {\n    position: absolute !important;\n    bottom: 0.75rem;\n    left: 0.5rem;\n    right: 0.5rem;\n\n    .ch-search-input {\n      flex: 1;\n\n      input {\n        width: 100%;\n      }\n    }\n\n    .ch-search-close {\n      margin-left: 0.5rem;\n    }\n  }\n\n  .ch-navigation-icon {\n    margin-right: 0.5rem;\n    margin-left: -0.5rem;\n\n    ", " {\n      display: none;\n    }\n  }\n\n  ", "\n  ", "\n"])), function (props) { return props.theme.roster.headerBorder; }, function (props) { return props.theme.roster.primaryText; }, function (props) { return (props.isSearching ? 'opacity: 0;' : ''); }, ellipsis, function (props) { return (props.isSearching ? 'opacity: 0;' : ''); }, function (props) { return (props.isSearching ? 'opacity: 0;' : ''); }, function (_a) {
    var theme = _a.theme;
    return theme.mediaQueries.min.md;
}, baseSpacing, baseStyles);
export var StyledName = styled.div(templateObject_6 || (templateObject_6 = __makeTemplateObject(["\n  flex-grow: 1;\n  min-width: 0;\n  line-height: 1.5;\n\n  .ch-name {\n    ", ";\n    font-size: 0.875rem;\n    color: ", ";\n  }\n\n  .ch-subtitle {\n    ", ";\n    font-size: 0.65rem;\n    color: ", ";\n  }\n"], ["\n  flex-grow: 1;\n  min-width: 0;\n  line-height: 1.5;\n\n  .ch-name {\n    ", ";\n    font-size: 0.875rem;\n    color: ", ";\n  }\n\n  .ch-subtitle {\n    ", ";\n    font-size: 0.65rem;\n    color: ", ";\n  }\n"])), ellipsis, function (props) { return props.theme.roster.primaryText; }, ellipsis, function (props) { return props.theme.roster.secondaryText; });
var templateObject_1, templateObject_2, templateObject_3, templateObject_4, templateObject_5, templateObject_6;
//# sourceMappingURL=Styled.js.map