// Copyright 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
import styled from 'styled-components';
var getPadding = function (props) {
    var sizing = props.sizing, leadingIcon = props.leadingIcon;
    return sizing === 'sm'
        ? "0.125rem 1.75rem 0.125rem " + (leadingIcon ? '1.3125rem' : '0.5rem')
        : "0.34375rem 1.75rem 0.34375rem " + (leadingIcon ? '1.3125rem' : '0.5rem');
};
export var StyledInputWrapper = styled.span(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  position: relative;\n\n  > .ch-icon {\n    position: absolute;\n    width: 1rem;\n    left: 0.1875rem;\n    position: absolute;\n    top: 54%;\n    transform: translateY(-50%);\n  }\n\n  > input {\n    padding: ", ";\n  }\n"], ["\n  position: relative;\n\n  > .ch-icon {\n    position: absolute;\n    width: 1rem;\n    left: 0.1875rem;\n    position: absolute;\n    top: 54%;\n    transform: translateY(-50%);\n  }\n\n  > input {\n    padding: ", ";\n  }\n"])), function (props) { return getPadding(props); });
export var StyledInput = styled.input(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n  align-items: center;\n  display: flex;\n  letter-spacing: -0.005625rem;\n  transition: box-shadow 0.05s ease-in;\n  background-color: ", ";\n  border: ", ";\n  border-radius: ", ";\n  box-shadow: ", ";\n  color: ", ";\n  font-size: ", ";\n  line-height: ", ";\n\n  &::placeholder {\n    color: ", ";\n  }\n\n  &:focus,\n  &[aria-invalid='true']:focus {\n    border: ", ";\n    box-shadow: ", ";\n    outline: none;\n  }\n\n  &[aria-invalid='true'] {\n    border: ", ";\n    box-shadow: ", ";\n  }\n\n  // Hides native clear button\n  &::-webkit-search-decoration,\n  ::-webkit-search-cancel-button,\n  ::-webkit-search-results-button,\n  ::-webkit-search-results-decoration {\n    display: none;\n  }\n\n  &::-ms-clear,\n  &::-ms-reveal {\n    display: none;\n    width: 0;\n    height: 0;\n  }\n"], ["\n  align-items: center;\n  display: flex;\n  letter-spacing: -0.005625rem;\n  transition: box-shadow 0.05s ease-in;\n  background-color: ", ";\n  border: ", ";\n  border-radius: ", ";\n  box-shadow: ", ";\n  color: ", ";\n  font-size: ", ";\n  line-height: ", ";\n\n  &::placeholder {\n    color: ", ";\n  }\n\n  &:focus,\n  &[aria-invalid='true']:focus {\n    border: ", ";\n    box-shadow: ", ";\n    outline: none;\n  }\n\n  &[aria-invalid='true'] {\n    border: ", ";\n    box-shadow: ", ";\n  }\n\n  // Hides native clear button\n  &::-webkit-search-decoration,\n  ::-webkit-search-cancel-button,\n  ::-webkit-search-results-button,\n  ::-webkit-search-results-decoration {\n    display: none;\n  }\n\n  &::-ms-clear,\n  &::-ms-reveal {\n    display: none;\n    width: 0;\n    height: 0;\n  }\n"])), function (props) { return props.theme.inputs.bgd; }, function (props) { return props.theme.inputs.border; }, function (props) { return props.theme.inputs.borderRadius; }, function (props) { return props.theme.inputs.shadow; }, function (props) { return props.theme.inputs.fontColor; }, function (props) { return props.theme.fontSizes.text.fontSize; }, function (props) { return props.theme.fontSizes.text.lineHeight; }, function (props) { return props.theme.inputs.placeholder; }, function (props) { return props.theme.inputs.focus.border; }, function (props) { return props.theme.inputs.focus.shadow; }, function (props) { return props.theme.inputs.error.border; }, function (props) { return props.theme.inputs.error.shadow; });
export var StyledClear = styled.button(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n  position: absolute;\n  top: 50%;\n  right: 0.125rem;\n  transform: translateY(-44%);\n  border: none;\n  background: none;\n  cursor: pointer;\n  display: ", ";\n\n  path {\n    fill: ", ";\n  }\n\n  &:active,\n  &:focus {\n    outline: none;\n  }\n"], ["\n  position: absolute;\n  top: 50%;\n  right: 0.125rem;\n  transform: translateY(-44%);\n  border: none;\n  background: none;\n  cursor: pointer;\n  display: ", ";\n\n  path {\n    fill: ", ";\n  }\n\n  &:active,\n  &:focus {\n    outline: none;\n  }\n"])), function (props) { return (props.active ? 'block' : 'none'); }, function (props) { return props.theme.inputs.clearBg; });
var templateObject_1, templateObject_2, templateObject_3;
//# sourceMappingURL=Styled.js.map